WIP:静的ページの作成
human-osaka-game-2017/rails-tutorial pull request #2
Opened 2018-12-13 03:20 UTC by shirapi

2018-12-13 09:33 UTC, taishi-matsumura commented
迷走しとるな笑

2018-12-14 01:48 UTC, taishi-matsumura requested changes
うん、だから 「Merge branch 'master' into static-pages」というコミットログが出るのは変です。
masterの内容をこのブランチに取り込みたいのであれば、static-pages「を」master「に」rebaseです。

2018-12-14 06:13 UTC, shuto-fujioka commented
aaa

2018-12-14 06:15 UTC, shuto-fujioka approved these changes

2018-12-14 06:31 UTC, taishi-matsumura approved these changes

2018-12-14 06:32 UTC, merged